### PR TITLE
Fix Enable Pin Logic

### LINKED ISSUE #155: Enable pin incorrect when using generic driver
The firmware doesn't properly enable A4988 drivers when using the generic driver option. Using TMC2209 standalone works for those drivers.

The enable pins are inverted states between those two options.

### PR DESCRIPTION
**Pull request by CTetford**
Use consistent enable pin logic for all drivers.

Increase maximum current for TMC2209 to 2A in accordance with BigTreeTech's published maximum continuous drive current.

Closes #155

### CODE REVIEW

File: ConfigurationValidation.hpp [hunk 1]
```diff
@@ -290,8 +290,8 @@
 
 #if (DEC_DRIVER_TYPE == DRIVER_TYPE_TMC2209_UART)
```
Comment (ClutchplateDude) [inline ConfigurationValidation.hpp:291]: What about the Focuser motor?

**Review by ClutchplateDude — CHANGES_REQUESTED** [review]

File: ConfigurationValidation.hpp (hunk 1 above)
Comment (CTetford) [reply ConfigurationValidation.hpp:291]: Ah my mistake. I forgot about that one. I'll update it.

File: ConfigurationValidation.hpp [hunk 2]
```diff
@@ -388,4 +388,32 @@
                 "ALT_OPERATING_CURRENT_SETTING is not defined. Please define the operating percentage of your motor in you local configuration file using the ALT_OPERATING_CURRENT_SETTING keyword."
         #endif
     #endif
-#endif
\ No newline at end of file
+#endif
+
+#if (FOCUS_STEPPER_TYPE != STEPPER_TYPE_NONE)
+    #if !defined(FOCUS_MICROSTEPPING)
+        #error "Altitude microstepping must be defined. Default is 4.0f for 28BYJ steppers, 4.0f for NEMA."
```
Comment (ClutchplateDude) [inline ConfigurationValidation.hpp]: Typo: Altitude

**Review by ClutchplateDude — CHANGES_REQUESTED** [review]

File: ConfigurationValidation.hpp (hunk 2 above)
Comment (CTetford) [reply ConfigurationValidation.hpp]: Fixed

**Review by ClutchplateDude — APPROVED** [review]
Looks good.
